[build]
  command = "npx tailwindcss -i ./frontend/styles/styles.css -o ./frontend/styles/output.css && npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  # Python runtime for serverless functions
  included_files = ["netlify/functions/**"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"